---
inherit_from: .rubocop_todo.yml

require:
  - rubocop-bridgetown
  - ./rubocop/bridgetown

inherit_gem:
  rubocop-bridgetown: .rubocop.yml

Bridgetown/NoPutsAllowed:
  Exclude:
    - rake/*.rake

AllCops:
  TargetRubyVersion: 3.2

Lint/NestedPercentLiteral:
  Exclude:
    - bridgetown-core/test/test_site.rb
Lint/RescueException:
  Exclude:
    - bridgetown-core/lib/bridgetown-core/watcher.rb
Lint/UnusedBlockArgument:
  Exclude:
    - bridgetown-core/lib/site_template/**/*.rb
Lint/Void:
  Exclude:
    - bridgetown-core/lib/bridgetown-core/concerns/site/configurable.rb
Metrics/AbcSize:
  Exclude:
    - bridgetown-core/lib/bridgetown-core/watcher.rb
Metrics/BlockLength:
  Exclude:
    - bridgetown-core/test/**/*.rb
    - bridgetown-core/lib/bridgetown-core/configuration.rb
    - bridgetown-core/rake/*.rake
Metrics/ClassLength:
  Exclude:
    - !ruby/regexp /bridgetown-core/features\/.*.rb$/
    - !ruby/regexp /bridgetown-core/test\/.*.rb$/
    - bridgetown-core/lib/bridgetown-core/configuration.rb
    - bridgetown-core/lib/bridgetown-core/collection.rb
Metrics/CyclomaticComplexity:
  Exclude:
    - bridgetown-core/lib/bridgetown-core/utils.rb
Layout/LineLength:
  Exclude:
    - !ruby/regexp /bridgetown-core/features\/.*.rb/
    - !ruby/regexp /bridgetown-core/test\/.*.rb$/
    - bridgetown-core/Rakefile
    - bridgetown-core/rake/*.rake
    - Gemfile
Metrics/ModuleLength:
  Exclude:
    - bridgetown-core/lib/bridgetown-core/filters.rb
Metrics/ParameterLists:
  Exclude:
    - bridgetown-core/lib/bridgetown-core/hooks.rb
Naming/HeredocDelimiterNaming:
  Exclude:
    - bridgetown-core/test/**/*.rb
Security/MarshalLoad:
  Exclude:
    - !ruby/regexp /bridgetown-core/test\/.*.rb$/
Security/YAMLLoad:
  Exclude:
    - !ruby/regexp /bridgetown-core/features\/.*.rb/
    - !ruby/regexp /bridgetown-core/test\/.*.rb$/
Style/FetchEnvVar:
  Enabled: false
Style/FrozenStringLiteralComment:
  Exclude:
    - bridgetown-core/lib/site_template/**/*.rb
Style/FormatStringToken:
  Exclude:
    - bridgetown-core/lib/bridgetown-core/utils/ansi.rb
    - bridgetown-core/lib/bridgetown-core/liquid_renderer/table.rb
Style/MixinUsage:
  Exclude:
    - bridgetown-core/test/helper.rb
