---
inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - ./rubocop/bridgetown

Bridgetown/NoPutsAllowed:
  Exclude:
    - rake/*.rake

AllCops:
  TargetRubyVersion: 2.4
  Include:
    - bridgetown-core/lib/**/*.rb
    - bridgetown-core/test/**/*.rb
  Exclude:
    - bridgetown-core/bin/**/*
    - bridgetown-core/exe/**/*
    - bridgetown-core/benchmark/**/*
    - bridgetown-core/script/**/*
    - bridgetown-core/vendor/**/*
    - bridgetown-core/tmp/**/*
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
Layout/IndentationWidth:
  Severity: error
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Lint/NestedPercentLiteral:
  Exclude:
    - bridgetown-core/test/test_site.rb
Layout/EmptyComment:
  Enabled: false
Layout/EndAlignment:
  Severity: error
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Lint/UnreachableCode:
  Severity: error
Lint/Void:
  Exclude:
    - bridgetown-core/lib/bridgetown-core/site.rb
Metrics/AbcSize:
  Max: 21
Metrics/BlockLength:
  Exclude:
    - bridgetown-core/test/**/*.rb
    - bridgetown-core/lib/bridgetown-core/configuration.rb
    - bridgetown-core/rake/*.rake
Metrics/ClassLength:
  Exclude:
    - !ruby/regexp /bridgetown-core/features\/.*.rb$/
    - !ruby/regexp /bridgetown-core/test\/.*.rb$/
    - bridgetown-core/lib/bridgetown-core/document.rb
    - bridgetown-core/lib/bridgetown-core/site.rb
    - bridgetown-core/lib/bridgetown-core/commands/serve.rb
    - bridgetown-core/lib/bridgetown-core/configuration.rb
  Max: 240
Metrics/CyclomaticComplexity:
  Exclude:
    - bridgetown-core/lib/bridgetown-core/utils.rb
    - bridgetown-core/lib/bridgetown-core/commands/serve.rb
Layout/LineLength:
  Exclude:
    - !ruby/regexp /bridgetown-core/features\/.*.rb/
    - bridgetown-core/Rakefile
    - bridgetown-core/rake/*.rake
    - Gemfile
  Max: 100
  Severity: warning
Metrics/MethodLength:
  CountComments: false
  Max: 20
  Severity: error
Metrics/ModuleLength:
  Max: 240
  Exclude:
    - bridgetown-core/lib/bridgetown-core/filters.rb
Metrics/ParameterLists:
  Max: 4
Metrics/PerceivedComplexity:
  Max: 8
Naming/FileName:
  Enabled: false
Naming/HeredocDelimiterNaming:
  Exclude:
    - bridgetown-core/test/**/*.rb
Naming/MemoizedInstanceVariableName:
  Exclude:
    - bridgetown-core/lib/bridgetown-core/convertible.rb
    - bridgetown-core/lib/bridgetown-core/drops/site_drop.rb
    - bridgetown-core/lib/bridgetown-core/drops/unified_payload_drop.rb
    - bridgetown-core/lib/bridgetown-core/page_without_a_file.rb
Security/MarshalLoad:
  Exclude:
    - !ruby/regexp /bridgetown-core/test\/.*.rb$/
    - bridgetown-core/lib/bridgetown-core/regenerator.rb
Security/YAMLLoad:
  Exclude:
    - !ruby/regexp /bridgetown-core/features\/.*.rb/
    - !ruby/regexp /bridgetown-core/test\/.*.rb$/
Style/AccessModifierDeclarations:
  Enabled: false
Style/Alias:
  EnforcedStyle: prefer_alias_method
Style/AndOr:
  Severity: error
Style/ClassAndModuleChildren:
  Exclude:
    - bridgetown-core/test/**/*.rb
Style/FrozenStringLiteralComment:
  EnforcedStyle: always
Style/Documentation:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/FormatStringToken:
  Exclude:
    - bridgetown-core/lib/bridgetown-core/utils/ansi.rb
    - bridgetown-core/lib/bridgetown-core/liquid_renderer/table.rb
Style/GuardClause:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashSyntax: # This now adheres to GitHub's newest Ruby style guide
  EnforcedStyle: ruby19
  SupportedStyles:
    # checks for 1.9 syntax (e.g. {a: 1}) for all symbol keys
    - ruby19
    # checks for hash rocket syntax for all hashes
    - hash_rockets
    # forbids mixed key syntaxes (e.g. {a: 1, :b => 2})
    - no_mixed_keys
    # enforces both ruby19 and no_mixed_keys styles
    - ruby19_no_mixed_keys
  # Force hashes that have a symbol value to use hash rockets
  UseHashRocketsWithSymbolValues: false
  # Do not suggest { a?: 1 } over { :a? => 1 } in ruby19 style
  PreferHashRocketsForNonAlnumEndingSymbols: false
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: true
Style/MixinUsage:
  Exclude:
    - bridgetown-core/test/helper.rb
Style/ModuleFunction:
  Enabled: false
Style/MultilineTernaryOperator:
  Severity: error
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%q": "{}"
    "%Q": "{}"
    "%r": "!!"
    "%s": "()"
    "%w": "()"
    "%W": "()"
    "%x": "()"
Style/RegexpLiteral:
  EnforcedStyle: percent_r
Style/RescueModifier:
  Enabled: false
Style/SafeNavigation:
  Exclude:
    - bridgetown-core/lib/bridgetown-core/document.rb
Style/SignalException:
  EnforcedStyle: only_raise
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
Style/SymbolArray:
  EnforcedStyle: brackets
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
