[build]
  base = "bridgetown-website/"
  command = "yarn deploy"
  publish = "output"

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

[[headers]]
  for = "*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = '''
      default-src 'self' https:;
      object-src  'none';
      worker-src  'none';
      manifest-src 'self';
      block-all-mixed-content;
      upgrade-insecure-requests;'''
    Strict-Transport-Security = "max-age=15552000; includeSubDomains"
    Referrer-Policy = "no-referrer-when-downgrade"
    Cache-Control = "public, max-age=604800, s-max-age=604800"

[[headers]]
  for = "/*.(png|jpg|js|css|svg|woff|ttf|eot|ico)"
  [headers.values]
    Cache-Control = "public, max-age=31536000, s-max-age=31536000"
