# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem "bridgetown", path: "../bridgetown"
gem "bridgetown-builder", path: "../bridgetown-builder"
gem "bridgetown-core", path: "../bridgetown-core"
gem "bridgetown-paginate", path: "../bridgetown-paginate"

gem "puma", "< 7"

gem "bridgetown-feed", "~> 3"
gem "bridgetown-quick-search", "~> 2.0"
gem "bridgetown-seo-tag", "~> 6.0"
gem "bridgetown-svg-inliner", "~> 2.0"

gem "gems", "~> 1.2"
gem "nokolexbor", "~> 0.4"

gem "ruby2js", "~> 5.1"
