# frozen_string_literal: true

source "https://rubygems.org"

gem "bridgetown", path: "../bridgetown"
gem "bridgetown-builder", path: "../bridgetown-builder"
gem "bridgetown-core", path: "../bridgetown-core"
gem "bridgetown-paginate", path: "../bridgetown-paginate"

group :bridgetown_plugins do
  gem "bridgetown-feed", "2.0.1", github: "bridgetownrb/bridgetown-feed"
  gem "bridgetown-quick-search", "1.1.2", github: "bridgetownrb/bridgetown-quick-search"
  gem "bridgetown-seo-tag", "4.0.1"
  gem "bridgetown-svg-inliner", "~> 1.0"
end

group :test, optional: true do
  gem "minitest"
  gem "minitest-profile"
  gem "minitest-reporters"
  gem "nokogiri"
  gem "rails-dom-testing"
  gem "shoulda"
end

gem "puma", "~> 5.2"
gem "regexp_parser", "2.0.3"
gem "ruby2js", "~> 4.0"
