source "https://rubygems.org"

gem 'bridgetown-core', path: '../bridgetown-core'
gem 'bridgetown-builder', path: '../bridgetown-builder'
gem 'bridgetown-paginate', path: '../bridgetown-paginate'
gem 'bridgetown', path: '../bridgetown'

gem "bridgetown-seo-tag", "3.0.5", :group => :bridgetown_plugins
gem "bridgetown-feed", "~> 1.0", :group => :bridgetown_plugins
gem "bridgetown-quick-search", "~> 1.0.3", group: :bridgetown_plugins

group :test, optional: true do
  gem "nokogiri"
  gem "minitest"
  gem "minitest-profile"
  gem "minitest-reporters"
  gem "shoulda"
  gem "rails-dom-testing"
end
