# frozen_string_literal: true

require "bridgetown"

Bridgetown.load_tasks

desc "Build the Bridgetown site for deployment"
task deploy: [
  :clean,
  :linthtml,
  "frontend:build",
] do
  Bundler.with_original_env do
    sh "bundle exec bridgetown build"
  end
end

task :linthtml do
  sh "yarn lint:html"
end

desc "Build the site in a test environment"
task :test do
  Bundler.with_original_env do
    sh "BRIDGETOWN_ENV=test bundle exec bridgetown build"
  end
end

desc "Runs the clean command"
task :clean do
  sh "bundle exec bridgetown clean"
end

namespace :frontend do
  desc "Build the frontend with Webpack for deployment"
  task :build do
    sh "yarn run webpack-build"
  end

  desc "Watch the frontend with Webpack during development"
  task :dev do
    sh "yarn run webpack-dev --color"
  rescue Interrupt
  end
end

task default: :deploy
