#!/usr/bin/env bash

script/branding

set -e

if [[ -z "$TEST_SUITE" ]]
then
  script/fmt
  script/test
  script/cucumber
elif [[ -x "script/$TEST_SUITE" ]]
then
  script/$TEST_SUITE
else
  echo "Unknown test suite."
  exit 1
fi
