#!/usr/bin/env bash
# Runs the `jekyll new` command and builds the default site as a sanity check

set -e

echo "$0: setting up tmp directory"
mkdir -p ./tmp
rm -Rf ./tmp/default-site

echo "$0: creating new default site"
bundle exec bridgetown new tmp/default-site
pushd tmp/default-site

echo "$0: respecifying the bridgetown install location"
ruby -e "contents = File.read('Gemfile'); File.write('Gemfile', contents.sub(/gem \"bridgetown\".*\\n/, 'gem \"bridgetown\", path: \"../../../\"'))"
echo "$0: installing default site dependencies"
BUNDLE_GEMFILE=Gemfile bundle install
echo "$0: building the default site"
BUNDLE_GEMFILE=Gemfile bundle exec bridgetown build --verbose --profile
popd
