---
inherit_from: ../.rubocop.yml

AllCops:
  Exclude:
    - "*.gemspec"
    - bin/**/*
    - exe/**/*
    - benchmark/**/*
    - script/**/*
    - vendor/**/*
    - tmp/**/*
    - test/source/**/*
    - test/resources/src/**/*.rb
    - lib/bridgetown-core/commands/base.rb
    - lib/bridgetown-core/commands/plugins.rb
    - lib/bridgetown-core/configurations/ruby2js/**/*
    - lib/bridgetown-core/rack/roda.rb
    - lib/site_template/TEMPLATES/**/*
    - lib/site_template/Rakefile
    - lib/site_template/config.ru
    - lib/site_template/config/**/*
    - lib/site_template/plugins/site_builder.rb
    - lib/site_template/server/roda_app.rb

Lint/ConstantDefinitionInBlock:
  Exclude:
    - test/test_liquid_extensions.rb
    - test/test_site.rb

Lint/MissingSuper:
  Exclude:
    - test/test_liquid_extensions.rb

Performance/CollectionLiteralInLoop:
  Exclude:
    - test/test_filters.rb

Style/OpenStructUse:
  Exclude:
    - test/**/*.rb

Style/StringConcatenation:
  Exclude:
    - test/test_apply_command.rb
