# frozen_string_literal: true

require "bundler/gem_tasks"

$LOAD_PATH.unshift File.expand_path("lib", __dir__)
require "bridgetown-core/version"

task spec: :test
require "rake/testtask"
Rake::TestTask.new(:test) do |test|
  test.libs << "lib" << "test"
  test.pattern = "test/**/test_*.rb"
  test.verbose = true
end
