require "bundler/gem_tasks"

$LOAD_PATH.unshift File.expand_path("lib", __dir__)
require "bridgetown-core/version"

Dir.glob("rake/**.rake").each { |f| import f }

#############################################################################
#
# Helper functions
#
#############################################################################

def name
  "bridgetown-core"
end

def version
  Bridgetown::VERSION
end

def gemspec_file
  "#{name}.gemspec"
end

def gem_file
  "#{name}-#{Gem::Version.new(version)}.gem"
end

#############################################################################
#
# Standard tasks
#
#############################################################################

task :spec => :test
require "rake/testtask"
Rake::TestTask.new(:test) do |test|
  test.libs << "lib" << "test"
  test.pattern = "test/**/test_*.rb"
  test.verbose = true
end