- name: site.time
  description: >-
    The current time (when you run the <code>bridgetown</code> command).
- name: site.resources
  description: >-
    A list of all resources (from pages, posts and other collections).
- name: site.static_files
  description: >-
    A list of all <a href="/docs/static-files/">static files</a> (i.e.
    files not processed by Bridgetown's converters or the Liquid renderer).
    Each file has five properties: <code>path</code>, <code>modified_time</code>,
    <code>name</code>, <code>basename</code> and <code>extname</code>.
- name: site.collections
  description: >-
    A list of all the collections (including posts).
- name: site.data
  description: >-
    A list containing the data loaded from the YAML files located in the <code>_data</code>
    directory.
- name: site.categories.CATEGORY
  description: >-
    The list of all resources in category <code>CATEGORY</code>.
- name: site.tags.TAG
  description: >-
    The list of all resources with tag <code>TAG</code>.
- name: site.config.url (Ruby) / site.url (Liquid) 
  description: >-
    Contains the url of your site as configured (for example, <code>url "http://mysite.com"</code>). For the <code>development</code>
    environment there is an
    exception: <code>site.config.url</code> will be set to the value of your localhost, as if you had manually configured <code>url "http://localhost:4000"</code>.
- name: "site.metadata"
  description: >-
    You can put metadata variables in <code>_data/site_metadata.yml</code> so
    they'll be easy to access and will regenerate pages when changed. This is a
    good place to put <code>&lt;head&gt;</code> content like site title,
    description, icon, social media handles, etc. Then you can reference
    <code>site.metadata.title</code>, etc. in your templates.
- name: "site.config.[KEY] (Ruby) / site.[KEY] (Liquid)"
  description: >-
    All the variables set via the command line and your configuration are available
    through the <code>site.config</code> variable. For example, if you have <code>foo "bar"</code> in
    your initializer, then it will be accessible <code>site.config.foo</code> (or <code>site.foo</code> in Liquid). Bridgetown does not parse changes to config files during live reload—you must restart Bridgetown to see changes to variables.
