---
inherit_from: ../.rubocop.yml

AllCops:
  Include:
    - lib/**/*.rb
    - spec/**/*.rb

Metrics/AbcSize:
  Exclude:
    - lib/bridgetown-builder/dsl/*
Metrics/MethodLength:
  Exclude:
    - lib/bridgetown-builder/dsl/*
