# frozen_string_literal: true

module Bridgetown
  module Routines
    class FrontendWatcher
      def initialize(site:)
        @site = site
      end

      def execute(instance) # rubocop:disable Metrics/AbcSize
        return unless watch_frontend?

        if Bridgetown::Utils.frontend_bundler_type(@site.config[:root_dir]) == :esbuild
          Bridgetown::Utils.update_esbuild_autogenerated_config(@site.config)
        end

        require "rake"
        Rake.with_application do |rake|
          begin
            rake.raw_load_rakefile
          rescue StandardError => e
            unless e.message.include?("No Rakefile found")
              Bridgetown.logger.error "Error Running Rake:", "#{e.message} (#{e.class})"
              e.backtrace[0..1].each { |backtrace_line| Bridgetown.logger.info backtrace_line }
            end
          end

          instance.ready!
          rake["frontend:dev"].invoke(true) if rake.tasks.any? { _1.name == "frontend:dev" }
        end
      end

      def name  = "Bridgetown Frontend Watcher"
      def key   = :frontend_watcher
      def tag   = { value: "Frontend", color: :blue }

      private

      def watch_frontend?
        return false if Bridgetown.environment.production?
        return false if @site.config["skip_frontend"]

        true
      end
    end
  end
end
